on:
  push:
    tags: v*.*
jobs:
  test:
    uses: ./.github/workflows/_test.yml
  build:
    needs: test
    uses: ./.github/workflows/_build.yml
  create-release-draft:
    runs-on: ubuntu-22.04
    needs: [test, build]
    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: artifacts/release_assets/
      - name: 🚀 Create GitHub release and upload asset files
        run: ./build.sh CreateGithubReleaseDraft
        env:
          GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
